### ISSUE TITLE
Link Piccnicc Domain to Heroku

### ISSUE THREAD

**Issue by katpas** [Jonty76/bubbles#353]
- [x] Connect Airport page to piccnicc.com/airport
- [x] Landing page is new conference page
- [x] SSL certificate

**Comment by rug1** [comment]
For Heroku SSL:
https://devcenter.heroku.com/articles/ssl-endpoint
https://devcenter.heroku.com/articles/ssl-beta
https://elements.heroku.com/addons/ssl

**Comment by katpas** [comment]
Done but need to wait to merge as stops local host from working.
