### ISSUE TITLE
Static Landing Page

### ISSUE THREAD

**Issue by katpas** [Jonty76/bubbles#421]

**Comment by rug1** [comment]
temporary image while waiting for real one
![temp-image](https://cloud.githubusercontent.com/assets/13667174/16800182/e6312470-48eb-11e6-9a93-316408a48f43.jpg)

**Comment by rug1** [comment]
Real Image
![shutterstock_350917211 piccnicc](https://cloud.githubusercontent.com/assets/13667174/16807825/d516ceda-4911-11e6-83d4-1329189e1cd0.jpg)

**Comment by rug1** [comment]
Edited Image
![shutterstock_350917211 piccnicc](https://cloud.githubusercontent.com/assets/13667174/16808317/f0795470-4913-11e6-972f-81477a2c5a04.png)
