### ISSUE TITLE
Remaining

### ISSUE THREAD

**Issue by katpas** [Jonty76/bubbles#453]
- [x]  Admin@ to verify SSL certificate (can't use piccnicc.com until done). 
- [x] Heroku SSL
- [x] Upgrade Heroku off Hobby Tier
- [x] Transfer Domain on Heroku.
- [x] Add Jonny's mail gun once domains are sorted
- [x] Add real Braintree details after bug-testing week. 
- [x] Get @naazy to delete old heroku app

**Comment by rug1** [comment]
For making braintree live:
https://developers.braintreepayments.com/start/go-live/node

**Comment by rug1** [comment]
This needs to be changed from the hardcoded email to what is commented out:
https://github.com/Jonty76/bubbles/blob/master/lib/mail-gun.js#L28

**Comment by katpas** [comment]
Delete Old Heroku App
