### ISSUE TITLE
Update Fonts - Pacifico for headers only

### ISSUE THREAD

**Issue by katpas** [Jonty76/bubbles#457]
- [ ] OZ Regular across app, details in dropbox folder (see email)
- [x] Only use Pacifico for header, remove from slogans

**Comment by katpas** [comment]
@rug1 This is done, and merged but the font only works on Safari. When I do it chrome I get this error in the browser console. 

![screen shot 2016-07-27 at 10 45 22](https://cloud.githubusercontent.com/assets/9627463/17171661/94986fac-53e9-11e6-9ac8-9ad905ec1e02.png)

**Comment by katpas** [comment]
http://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts

That should solve it.

**Comment by katpas** [comment]
@rug1 I tried to install that module, couldn't get the bundle to work using it though. 
Got the error "can't resolve module object object in main.js (which is in the styles folder)". Also need to make sure we're making changes to the right server. 

Any ideas?

**Comment by rug1** [comment]
firefox errors
![screen shot 2016-08-15 at 15 53 45](https://cloud.githubusercontent.com/assets/13667174/17668345/be81d5f8-6300-11e6-8543-74ab2239ab78.png)

**Comment by rug1** [comment]
For stackoverflow:
![screen shot 2016-08-15 at 15 51 52](https://cloud.githubusercontent.com/assets/13667174/17668615/14ed5c9a-6302-11e6-8485-d4191bee613f.png)
![screen shot 2016-08-15 at 15 53 45](https://cloud.githubusercontent.com/assets/13667174/17668619/16e31ec2-6302-11e6-86f7-846fb0e35160.png)

**Comment by rug1** [comment]
http://stackoverflow.com/questions/38957776/chrome-and-firefox-unable-to-parse-and-decode-font

**Comment by katpas** [comment]
Roboto set as font.
